export const listOfEmployees = [
    {
        firstName: "Paul",
        lastName: "Kellen",
        startDate: "2000-03-29",
        department: "Sales",
        dateOfBirth: "1978-12-27",
        street: "1 main street",
        city: "Naloma",
        state: "Alabama",
        zipCode: "48544",
    },
    {
        firstName: "Alex",
        lastName: "Trem",
        startDate: "2022-03-29",
        department: "Engineering",
        dateOfBirth: "1985-05-22",
        street: "5 Hall of Fame",
        city: "Honolulu",
        state: "Hawaii",
        zipCode: "94544",
    },
    {
        firstName: "Ezekiel",
        lastName: "Lion",
        startDate: "2020-05-19",
        department: "Legal",
        dateOfBirth: "1995-09-17",
        street: "15 Street Liberty",
        city: "New York",
        state: "New York",
        zipCode: "11544",
    },
    {
        firstName: "Elijah",
        lastName: "Rasta",
        startDate: "2015-02-09",
        department: "Marketing",
        dateOfBirth: "1990-12-31",
        street: "1 Place of Freedom",
        city: "Los Angeles",
        state: "California",
        zipCode: "35584",
    },
    {
        firstName: "Lucien",
        lastName: "Larowsky",
        startDate: "2015-07-19",
        department: "Sales",
        dateOfBirth: "1991-03-12",
        street: "18 Hall of Dark",
        city: "Los Ageles",
        state: "California",
        zipCode: "45648",
    },
    {
        firstName: "Hugo",
        lastName: "Ghlory",
        startDate: "2002-01-29",
        department: "Marketing",
        dateOfBirth: "1975-09-02",
        street: "658 Road Olympus",
        city: "Mimami",
        state: "Florida",
        zipCode: "97658",
    },
    {
        firstName: "Florent",
        lastName: "Mano",
        startDate: "2021-09-29",
        department: "Marketing",
        dateOfBirth: "1995-01-03",
        street: "49 Bad Road",
        city: "Georgio",
        state: "Georgia",
        zipCode: "21568",
    },
    {
        firstName: "Isa",
        lastName: "Loiseau",
        startDate: "2012-08-19",
        department: "Legal",
        dateOfBirth: "1979-04-02",
        street: "558 Road Okooala",
        city: "El Paso",
        state: "Texas",
        zipCode: "65545",
    },
    {
        firstName: "Linda",
        lastName: "Desuza",
        startDate: "2002-03-15",
        department: "Sales",
        dateOfBirth: "1989-05-02",
        street: "658 Road Avenue",
        city: "Albuquerque",
        state: "New Mexico",
        zipCode: "25487",
    },
    {
        firstName: "Lucia",
        lastName: "Martinez",
        startDate: "2002-03-15",
        department: "Sales",
        dateOfBirth: "1989-05-02",
        street: "65 Lost Avenue",
        city: "Hidao",
        state: "Texas",
        zipCode: "57842",
    },
    {
        firstName: "Florian",
        lastName: "Gentile",
        startDate: "2012-12-15",
        department: "Marketing",
        dateOfBirth: "1979-04-02",
        street: "32 Hall Of Delivery",
        city: "Molitor",
        state: "New Mexico",
        zipCode: "98784",
    },
]