export const listOfEmployees = [
    {
        firstName: "Paul",
        lastName: "Kellen",
        startDate: "2000-03-29",
        department: "Sales",
        dateOfBirth: "1978-12-27",
        street: "1 main street",
        city: "Naloma",
        state: "Alabama",
        zipCode: "48544",
    },
    {
        firstName: "Alex",
        lastName: "Trem",
        startDate: "2022-03-29",
        department: "Engineering",
        dateOfBirth: "1985-05-22",
        street: "5 Hall of Fame",
        city: "Honolulu",
        state: "Hawaii",
        zipCode: "94544",
    },
    {
        firstName: "Ezekiel",
        lastName: "Lion",
        startDate: "2020-05-19",
        department: "Legal",
        dateOfBirth: "1995-09-17",
        street: "15 Street Liberty",
        city: "New York",
        state: "New York",
        zipCode: "11544",
    },
    {
        "firstName": "Elijah",
        "lastName": "Rasta",
        "startDate": "2015-02-09",
        "department": "Marketing",
        "dateOfBirth": "1990-12-31",
        "street": "1 Place of Freedom",
        "city": "Los Angeles",
        "state": "California",
        "zipCode": "35584",
    },
]